Sprint 1
ClevertecFrontendLab/sprint1-Irina-coud pull request #1
Opened 2023-02-01 23:33 UTC by Irina-coud

2023-02-01 23:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Irina-coud/1675294595/content-window.png)

2023-02-01 23:57 UTC, ValadzkoAliaksei requested changes

2023-02-01 23:57 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/styled-components": "^5.1.26",
![image](https://user-images.githubusercontent.com/61273546/216193796-d9a61cde-6b87-410f-8d56-08e2d37d5856.png)
выравнивание по левому краю необходимо, согласно дизайну

2023-02-01 23:57 UTC, ValadzkoAliaksei commented on package.json
> +    "@reduxjs/toolkit": "^1.9.2",
![image](https://user-images.githubusercontent.com/61273546/216194840-3a3ff587-da60-462f-93ae-1f0e2f5d5109.png)
цвет текста не согласно дизайну

2023-02-01 23:57 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/react-redux": "^7.1.25",
![image](https://user-images.githubusercontent.com/61273546/216195019-5e072fe9-e2e4-4280-bf9d-06bcad1eab6a.png)
Расположение даты и фамилии не согласно дизайну

2023-02-01 23:57 UTC, ValadzkoAliaksei commented on package.json
> +    "react-redux": "^8.0.5",
![image](https://user-images.githubusercontent.com/61273546/216195272-aa09ec9d-6869-4b14-9139-eac15d8c07b1.png)
Кнопка и футер. совершенно не согласно дизайну.

2023-02-01 23:57 UTC, ValadzkoAliaksei commented on package.json
> +    "react-redux": "^8.0.5",
и это я лишь только страницу книги по id на 320 px глянул. Остальное гляньте плз сами, что бы стили совпадали  с стилями в фигме.

2023-02-02 09:10 UTC, ValadzkoAliaksei commented
Все очень кривенько. но я апрув кину)
исправьте плз ко второму спринту недочеты, отличные от дизайна...

2023-02-02 09:11 UTC, ValadzkoAliaksei approved these changes

2023-02-02 09:17 UTC, merged